### ISSUE TITLE
"command" type of email is broken

### ISSUE THREAD

**Issue by dernasherbrezon** [twaugh/journal-brief#62]
```
DEBUG:cli:email={'suppress_empty': True, 'command': 'sendmail -i -t', 'to': ['info@example.com'], 'from': 'bug@example.com'} from config
DEBUG:cli:email={'suppress_empty': True, 'command': 'sendmail -i -t', 'to': ['info@example.com'], 'from': 'bug@example.com'} from config
DEBUG:cli:mime_email=True from config
Traceback (most recent call last):
  File "/usr/local/bin/journal-brief", line 11, in <module>
    load_entry_point('journal-brief==1.1.7', 'console_scripts', 'journal-brief')()
  File "/usr/local/lib/python3.5/dist-packages/journal_brief-1.1.7-py3.5.egg/journal_brief/cli/main.py", line 320, in run
  File "/usr/local/lib/python3.5/dist-packages/journal_brief-1.1.7-py3.5.egg/journal_brief/cli/main.py", line 314, in run
  File "/usr/local/lib/python3.5/dist-packages/journal_brief-1.1.7-py3.5.egg/journal_brief/cli/main.py", line 252, in send_email
  File "/usr/lib/python3.5/subprocess.py", line 385, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.5/subprocess.py", line 786, in communicate
    self._stdin_write(input)
  File "/usr/lib/python3.5/subprocess.py", line 741, in _stdin_write
    self.stdin.write(input)
TypeError: write() argument must be str, not MIMEText
```

I replaced ```input=message``` with ```input=message.as_string()``` and it solved the problem.

**Comment by kpfleming** [comment]
I'll tackle this one, since I added the email support. I ran into some differences in behavior in the MIME library in various Python versions, and this may be one of them.

Would you do me a favor and try a 'dry-run' as well, with 'command' mode configured? That should also fail, for the same reason, but it would be good to confirm before making any changes.

**Comment by dernasherbrezon** [comment]
Actually it was not failing in the dry-run mode. I guess because dry-run just serialise this into string and output, rather than passing to subprocess. Anyway, here is the output:

```
Email to be delivered via 'sendmail -i -t'
------
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
X-Journal-Brief-Version: 1.1.7
From: bug@example.com
To: info@example.com
Subject: test subject

Nov 25 23:45:33 raspberrypi ?[1844]: hello test
```

Also I noticed default instructions suggest putting into /etc/cron.d/. These location is for root user. That means all email and other config is no-op if I prepare it under non-root user.

**Comment by kpfleming** [comment]
Thanks I suspected that would be the case. `print()` will call `__str__()` on the object to convert it into a string, but apparently `subprocess.run()` will not.

Your comments about the cron configuration are valid, but belong in a different issue. Also, most usage of this tool is done by `root`, since most of the journals on the system are only accessible to `root`.

**Comment by twaugh** [comment]
Thanks!
